/*
 * Copyright (C) 2014 hdm
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package openseihonintei;

/**
 *
 * @author hdm
 */
public class SetaiPanel extends javax.swing.JPanel {
    //共通部分
    public static boolean DebugMode = false;
    public static void logDebug(String str) {
        if (DebugMode) {
            System.out.println(str);
        }
    }
    
    /**
     * Creates new form SetaiPanel
     */
    public SetaiPanel() {
        initComponents();
    }

    public void setChecked(boolean chk) {
        checked.setSelected(chk);
    }
    public boolean getChecked() {
        return checked.isSelected();
    }
    public void setMyouji(String Myouji) {
        String wk = textName.getText();
        if (wk.startsWith(Myouji)) {
            return;
        }
        textName.setText(Myouji + "　" + wk);
    }
    /**
     * 認定年齢を算出：4月1日時点の年齢、ただし、マイナスになる場合は０とする。
     * @param nendo 
     */
    public void setNenrei(int nendo) {
        //日付を取得(生年月日)
        String ymdID = textYmd.getID();
        try {
            Long.parseLong(ymdID);
        } catch (Exception e) {
            textNenrei.setText("");
            return;
        }
        String y = ymdID.substring(0, 4);
        String m = ymdID.substring(4, 6);
        String d = ymdID.substring(6, 8);
        //指定年度4月1日時点の年齢を算出
        DebugMode = true;
        logDebug(y + "//" + m + "//" + d);
        String y41 = "" + nendo;
        //当年度の誕生日を算出
        int birthYmdThisYear = Integer.parseInt(nendo + m + d);
        if (Integer.parseInt(m) <= 3) {
            //1-3月生まれの場合は年度＋１ (月日部分:0000)
            birthYmdThisYear = birthYmdThisYear + 10000;
        }
        //ret : 年齢（戻り値） floor:切り捨て　ceil:切り上げ
        int yyyy1 = Integer.parseInt(y);
        int yyyy2 = nendo;
        if (Integer.parseInt(m) <= 3) {
            //1-3月生まれの場合は年度＋１ (月日部分:0000)
            yyyy2 = yyyy2 + 1;
        }
        int ret = yyyy2 - yyyy1;
        //当年度の誕生日を過ぎていなかったら調整(4月1日前後の誕生日に注意)
        int thisYear41 = (nendo * 10000 + 401);
        logDebug("当年度の４月１日：" + thisYear41);
        logDebug("当年度の誕生日：" + birthYmdThisYear);
        //誕生日過ぎているか
        if (thisYear41 < birthYmdThisYear) {
            ret = ret - 1;
        }
        //年齢がマイナスになる場合は０に変更
        logDebug("算出値：" + ret);
        if (ret < 0) {
            ret = 0;
        }
        textNenrei.setText("" + ret);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checked = new javax.swing.JCheckBox();
        textName = new javax.swing.JTextField();
        textYmd = new OpenSeiho.textYmdPanel();
        jLabel1 = new javax.swing.JLabel();
        textNenrei = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setFocusCycleRoot(true);
        setFocusTraversalPolicy(null);
        setFocusTraversalPolicyProvider(true);
        setPreferredSize(new java.awt.Dimension(686, 64));

        org.openide.awt.Mnemonics.setLocalizedText(checked, org.openide.util.NbBundle.getMessage(SetaiPanel.class, "SetaiPanel.checked.text")); // NOI18N
        checked.setToolTipText(org.openide.util.NbBundle.getMessage(SetaiPanel.class, "SetaiPanel.checked.toolTipText")); // NOI18N

        textName.setText(org.openide.util.NbBundle.getMessage(SetaiPanel.class, "SetaiPanel.textName.text")); // NOI18N

        textYmd.setCaption(org.openide.util.NbBundle.getMessage(SetaiPanel.class, "SetaiPanel.textYmd.caption")); // NOI18N
        textYmd.setTextYMD(org.openide.util.NbBundle.getMessage(SetaiPanel.class, "SetaiPanel.textYmd.textYMD")); // NOI18N
        textYmd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textYmdFocusLost(evt);
            }
        });
        textYmd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                textYmdPropertyChange(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(SetaiPanel.class, "SetaiPanel.jLabel1.text")); // NOI18N

        textNenrei.setEditable(false);
        textNenrei.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textNenrei.setText(org.openide.util.NbBundle.getMessage(SetaiPanel.class, "SetaiPanel.textNenrei.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(SetaiPanel.class, "SetaiPanel.jLabel2.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(15, 15, 15)
                        .add(checked)
                        .add(18, 18, 18)
                        .add(textName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(textYmd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(textNenrei, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)))
                .add(0, 147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(checked)
                    .add(textName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(textNenrei)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(textYmd, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textYmdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textYmdPropertyChange
        // TODO add your handling code here:
        //DebugMode = true;
        //logDebug(evt.getPropertyName());
    }//GEN-LAST:event_textYmdPropertyChange

    private void textYmdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textYmdFocusLost
        // TODO add your handling code here:
        //logDebug("now!");
    }//GEN-LAST:event_textYmdFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checked;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textNenrei;
    private OpenSeiho.textYmdPanel textYmd;
    // End of variables declaration//GEN-END:variables
}
